#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_knits = env_modules.Clone()
env_knits.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_knits.add_source_files(env.modules_sources, "./editor/*.cpp")

if env["tests"]:
    env_knits.add_source_files(env.modules_sources, "./tests/*.cpp")
